//! Function pointer type aliases for dlsym-resolved RCL functions.
//!
//! These cannot be generated by bindgen (we don't link to rcl, we dlsym it).
//! The signatures are identical across Humble and Jazzy.

// Type names intentionally match C headers for FFI clarity.
#![allow(non_camel_case_types)]

use std::ffi::{c_char, c_void};

use crate::opaque::*;
use crate::rosidl_message_type_support_t;

/// Return type for rcl functions. 0 = RCL_RET_OK.
pub type rcl_ret_t = i32;

/// `rcl_publisher_init(publisher, node, type_support, topic_name, options) → rcl_ret_t`
pub type FnRclPublisherInit = unsafe extern "C" fn(
    *mut rcl_publisher_t,
    *const rcl_node_t,
    *const rosidl_message_type_support_t,
    *const c_char,
    *const rcl_publisher_options_t,
) -> rcl_ret_t;

/// `rcl_publish(publisher, ros_message, allocation) → rcl_ret_t`
pub type FnRclPublish = unsafe extern "C" fn(
    *const rcl_publisher_t,
    *const c_void,
    *mut rmw_publisher_allocation_t,
) -> rcl_ret_t;

/// `rcl_subscription_init(subscription, node, type_support, topic_name, options) → rcl_ret_t`
pub type FnRclSubscriptionInit = unsafe extern "C" fn(
    *mut rcl_subscription_t,
    *const rcl_node_t,
    *const rosidl_message_type_support_t,
    *const c_char,
    *const rcl_subscription_options_t,
) -> rcl_ret_t;

/// `rcl_take(subscription, ros_message, message_info, allocation) → rcl_ret_t`
pub type FnRclTake = unsafe extern "C" fn(
    *const rcl_subscription_t,
    *mut c_void,
    *mut rmw_message_info_t,
    *mut rmw_subscription_allocation_t,
) -> rcl_ret_t;
