//! FFI type definitions mirroring ROS 2 RCL and rosidl C headers.
//!
//! Struct types are generated by bindgen from the actual C headers and checked
//! into `src/bindings/<distro>.rs`. Opaque handle types and function pointer
//! aliases are hand-written (shared across distros).
//!
//! # Feature flags
//!
//! Exactly one distro feature must be enabled: `humble` or `jazzy`.
//! The `generate-bindings` feature re-runs bindgen (developer workflow only).

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]

// Enforce exactly one distro feature.
#[cfg(all(feature = "humble", feature = "jazzy"))]
compile_error!("Enable exactly one distro feature: `humble` or `jazzy` (both are set)");

#[cfg(not(any(feature = "humble", feature = "jazzy")))]
compile_error!("Enable exactly one distro feature: `humble` or `jazzy` (neither is set)");

mod bindings;
pub mod fn_types;
pub mod opaque;

// Re-export everything from bindgen-generated bindings.
pub use bindings::*;

// Re-export opaque types at crate root for convenience.
pub use opaque::*;

// Re-export function pointer types at crate root.
pub use fn_types::*;

// ---------------------------------------------------------------------------
// Convenience aliases (stable across distros)
// ---------------------------------------------------------------------------

/// Alias for `builtin_interfaces__msg__Time`.
pub type BuiltinTime = builtin_interfaces__msg__Time;

/// Alias for `rosidl_typesupport_introspection_c__MessageMember`.
pub type MessageMember = rosidl_typesupport_introspection_c__MessageMember;

/// Alias for `rosidl_typesupport_introspection_c__MessageMembers`.
pub type MessageMembers = rosidl_typesupport_introspection_c__MessageMembers;

/// Field type value indicating an embedded message (sub-struct).
///
/// Matches `rosidl_typesupport_introspection_c__ROS_TYPE_MESSAGE` from field_types.h.
/// Hardcoded because the enum constant name in bindgen output is unwieldy and the
/// value (18) is stable across all ROS 2 distros.
pub const ROS_TYPE_MESSAGE: u8 = 18;

/// The identifier string used to request the introspection_c typesupport.
pub const TYPESUPPORT_INTROSPECTION_C_IDENTIFIER: &[u8] =
    b"rosidl_typesupport_introspection_c\0";
